package finalAssignment.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import finalAssignment.control.StudentManager;
import finalAssignment.model.Student;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.List;

public class StudentManageGui extends BaseView {
    private JButton addStudentButton;
    private JButton viewStudentButton;
    private JButton searchStudentButton;
    private JButton deleteStudentButton;
    private JButton updateStudentButton;
    private JButton backFromStudentButton;
    private JPanel mainPanel;

    public StudentManageGui() {

        addStudentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = BaseView.getCurrentFrame();
                currentFrame.getContentPane().removeAll();
                CreateStudentGui createStudentGui = new CreateStudentGui();
                currentFrame.setContentPane(createStudentGui.getMainPanel());
                currentFrame.setVisible(true);
            }
        });
        viewStudentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = BaseView.getCurrentFrame();
                currentFrame.getContentPane().removeAll();
                ViewStudentGui viewStudentGui = new ViewStudentGui();
                currentFrame.setContentPane(viewStudentGui.getMainPanel());

                StudentManager studentManager = new StudentManager();
                List<Student> student_list = studentManager.view_all_students();

                for (Student student : student_list) {
                    viewStudentGui.getViewStudentTextArea().append(student.toString());
                }
                currentFrame.setVisible(true);
            }
        });
        searchStudentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = BaseView.getCurrentFrame();
                currentFrame.getContentPane().removeAll();
                GetNameViewStudent getNameViewStudent = new GetNameViewStudent();
                currentFrame.setContentPane(getNameViewStudent.getMainPanel());
                currentFrame.setVisible(true);
            }
        });
        deleteStudentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = BaseView.getCurrentFrame();
                currentFrame.getContentPane().removeAll();
                GetIdDeleteStudentGui getIdDeleteStudentGui = new GetIdDeleteStudentGui();
                currentFrame.setContentPane(getIdDeleteStudentGui.getMainPanel());
                currentFrame.setVisible(true);
            }
        });
        backFromStudentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = BaseView.getCurrentFrame();
                currentFrame.getContentPane().removeAll();
                MainGui mainGui = new MainGui();
                currentFrame.setContentPane(mainGui.getMainPanel());
                currentFrame.setVisible(true);
            }
        });
        updateStudentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = BaseView.getCurrentFrame();
                currentFrame.getContentPane().removeAll();
                GetIdUpdateStudentGui getIdUpdateStudentGui = new GetIdUpdateStudentGui();
                currentFrame.setContentPane(getIdUpdateStudentGui.getMainPanel());
                currentFrame.setVisible(true);
            }
        });
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        addStudentButton = new JButton();
        addStudentButton.setText("1. Add new student");
        mainPanel.add(addStudentButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        viewStudentButton = new JButton();
        viewStudentButton.setText("2. View all students");
        mainPanel.add(viewStudentButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchStudentButton = new JButton();
        searchStudentButton.setText("3. Search students");
        mainPanel.add(searchStudentButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteStudentButton = new JButton();
        deleteStudentButton.setText("4. Delete students");
        mainPanel.add(deleteStudentButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        updateStudentButton = new JButton();
        updateStudentButton.setText("5. Update student");
        mainPanel.add(updateStudentButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backFromStudentButton = new JButton();
        backFromStudentButton.setText("6. Back to main menu");
        mainPanel.add(backFromStudentButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
